### ISSUE TITLE
question

### ISSUE THREAD

**Issue by aniketstark** [Neternels/NetHunter-MT6768#2]
is this kernel support external wifi adapters
if support's 
how can i flash it

**Comment by m1kuwu** [comment]
Same question

**Comment by Kharism404** [comment]
Anyone already flash this kernel?

**Comment by aniketstark** [comment]
@Kharism404 @DarindaDraX  I already flash it using also unofficial ROM. But didn't support external 
Now I moved to Poco F1 it's official listed in nethunter device list

**Comment by Kharism404** [comment]
> @Kharism404 @DarindaDraX I already flash it using also unofficial ROM. But didn't support external Now I moved to Poco F1 it's official listed in nethunter device list

How do you flash this kernel? I wanna try to my Redmi Note 9 but the kernel format just like folder with bunch of file. Sould i make it to ZIP file?

**Comment by aniketstark** [comment]
using aosp rom but because of that rom my device get hard bricked i dunno is this because of kernel or rom or my mistake 
but i recommend you this kernel wont work i tried tplink w722n v2/v3 and t2u plus it doesn't show any thing 
currently i am using poco f1 prolly in future i can't reply on this thread that i opened long time ago
